#include "AppBarBase.h"

#include <e3/ViewFactory.h>
#include "NoLimitsValues.h"

AppBarBase::AppBarBase(e3::Element* pParent)
	: e3::Element(pParent)
{
        this->SetWidth("100%");
        this->SetHeight("60dp");
        this->SetOrientation((e3::EOrientation)0);
        this->SetAlignItemsHor((e3::EAlignment)3);
        this->SetPaddingLeft("100dp");
        this->SetPaddingRight("100dp");
    e3::Element* pElement1 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    AddElement(pElement1);
        pElement1->SetHeight("100%");
        e3::FontIcon* pFontIcon1 = e3::ViewFactory::CreateFontIcon();
        pElement1->AddElement(pFontIcon1);
        pFontIcon1->SetWidth("30dp");
        pFontIcon1->SetAspectRatio(1.000000);
        pFontIcon1->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon1->SetCharcode(59660);
        pFontIcon1->SetColor(glm::vec4(255));
        e3::FontIcon* pFontIcon2 = e3::ViewFactory::CreateFontIcon();
        pElement1->AddElement(pFontIcon2);
        pFontIcon2->SetWidth("30dp");
        pFontIcon2->SetAspectRatio(1.000000);
        pFontIcon2->SetMarginLeft("20dp");
        pFontIcon2->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon2->SetCharcode(59650);
        pFontIcon2->SetColor(glm::vec4(255));
    e3::Element* pElement2 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement1->AddElement(pElement2);
        pElement2->SetWidth("35dp");
        pElement2->SetAspectRatio(1.000000);
        pElement2->SetMarginLeft("20dp");
        pElement2->SetBorderRadius(glm::vec4(0.5));
        pElement2->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
        e3::FontIcon* pFontIcon3 = e3::ViewFactory::CreateFontIcon();
        pElement2->AddElement(pFontIcon3);
        pFontIcon3->SetWidth("25dp");
        pFontIcon3->SetAspectRatio(1.000000);
        pFontIcon3->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon3->SetCharcode(59658);
        pFontIcon3->SetColor(glm::vec4(255));
    mMissions = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement1->AddElement(mMissions);
        mMissions->SetWidth("35dp");
        mMissions->SetAspectRatio(1.000000);
        mMissions->SetMarginLeft("20dp");
        mMissions->SetBorderRadius(glm::vec4(0.5));
        mMissions->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
        e3::FontIcon* pFontIcon4 = e3::ViewFactory::CreateFontIcon();
        mMissions->AddElement(pFontIcon4);
        pFontIcon4->SetWidth("20dp");
        pFontIcon4->SetAspectRatio(1.000000);
        pFontIcon4->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon4->SetCharcode(59654);
        pFontIcon4->SetColor(glm::vec4(255));
                BadgeIcon* pCustomView1 = new BadgeIcon();
        mMissions->AddElement(pCustomView1);
    e3::Element* pElement3 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement1->AddElement(pElement3);
        pElement3->SetMarginLeft("20dp");
    e3::Element* pElement4 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement3->AddElement(pElement4);
        pElement4->SetWidth("30dp");
        pElement4->SetAspectRatio(1.000000);
        pElement4->SetBackgroundColor(glm::vec4(46.000000, 23.000000, 105.000000, 255.000000));
        pElement4->SetShapeType((e3::EShapeType)1);
        pElement4->SetBorderSize("2dp");
        pElement4->SetBorderColor(glm::vec4(255, 255, 255, 100));
        e3::FontIcon* pFontIcon5 = e3::ViewFactory::CreateFontIcon();
        pElement4->AddElement(pFontIcon5);
        pFontIcon5->SetWidth("14dp");
        pFontIcon5->SetAspectRatio(1.000000);
        pFontIcon5->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon5->SetCharcode(59657);
        pFontIcon5->SetColor(glm::vec4(255));
        e3::Text* pText1 = e3::ViewFactory::CreateText();
        pElement3->AddElement(pText1);
        pText1->SetMarginLeft("10dp");
        pText1->SetText("72");
        pText1->SetFontStyle((e3::EFontStyle)2);
        pText1->SetFontSize("14dp");
        pText1->SetTextColor(glm::vec4(255));
    e3::Element* pElement5 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    AddElement(pElement5);
        pElement5->SetWidth("40%");
        pElement5->SetHeight("100%");
    e3::Element* pElement6 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement5->AddElement(pElement6);
        pElement6->SetMarginLeft("20dp");
    e3::Element* pElement7 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement6->AddElement(pElement7);
        pElement7->SetWidth("25dp");
        pElement7->SetAspectRatio(1.000000);
        pElement7->SetBackgroundColor(glm::vec4(255));
        pElement7->SetShapeType((e3::EShapeType)1);
        e3::FontIcon* pFontIcon6 = e3::ViewFactory::CreateFontIcon();
        pElement7->AddElement(pFontIcon6);
        pFontIcon6->SetWidth("14dp");
        pFontIcon6->SetAspectRatio(1.000000);
        pFontIcon6->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon6->SetCharcode(59652);
        pFontIcon6->SetColor(glm::vec4(0, 0, 0, 255));
        e3::Text* pText2 = e3::ViewFactory::CreateText();
        pElement6->AddElement(pText2);
        pText2->SetMarginLeft("5dp");
        pText2->SetText("175 239");
        pText2->SetFontStyle((e3::EFontStyle)2);
        pText2->SetFontSize("14dp");
        pText2->SetTextColor(glm::vec4(255));
    e3::Element* pElement8 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement6->AddElement(pElement8);
        pElement8->SetMarginLeft("5dp");
        pElement8->SetWidth("1dp");
        pElement8->SetHeight("10dp");
        pElement8->SetBackgroundColor(glm::vec4(255, 255, 255, 100));
    e3::Element* pElement9 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement5->AddElement(pElement9);
        pElement9->SetMarginLeft("20dp");
        e3::FontIcon* pFontIcon7 = e3::ViewFactory::CreateFontIcon();
        pElement9->AddElement(pFontIcon7);
        pFontIcon7->SetWidth("20dp");
        pFontIcon7->SetAspectRatio(1.000000);
        pFontIcon7->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon7->SetCharcode(59656);
        pFontIcon7->SetColor(glm::vec4(253.000000, 212.000000, 26.000000, 255.000000));
        e3::Text* pText3 = e3::ViewFactory::CreateText();
        pElement9->AddElement(pText3);
        pText3->SetMarginLeft("5dp");
        pText3->SetText("721");
        pText3->SetFontStyle((e3::EFontStyle)2);
        pText3->SetFontSize("14dp");
        pText3->SetTextColor(glm::vec4(253.000000, 212.000000, 26.000000, 255.000000));
    e3::Element* pElement10 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement9->AddElement(pElement10);
        pElement10->SetMarginLeft("10dp");
        pElement10->SetWidth("18dp");
        pElement10->SetAspectRatio(1.000000);
        pElement10->SetShapeType((e3::EShapeType)1);
        pElement10->SetBackgroundColor(glm::vec4(93.000000, 215.000000, 128.000000, 255.000000));
        e3::FontIcon* pFontIcon8 = e3::ViewFactory::CreateFontIcon();
        pElement10->AddElement(pFontIcon8);
        pFontIcon8->SetWidth("14dp");
        pFontIcon8->SetAspectRatio(1.000000);
        pFontIcon8->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon8->SetCharcode(59653);
        pFontIcon8->SetColor(glm::vec4(0, 0, 0, 255));
    e3::Element* pElement11 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement9->AddElement(pElement11);
        pElement11->SetMarginLeft("5dp");
        pElement11->SetWidth("1dp");
        pElement11->SetHeight("10dp");
        pElement11->SetBackgroundColor(glm::vec4(255, 255, 255, 100));
    e3::Element* pElement12 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement5->AddElement(pElement12);
        pElement12->SetMarginLeft("20dp");
        e3::FontIcon* pFontIcon9 = e3::ViewFactory::CreateFontIcon();
        pElement12->AddElement(pFontIcon9);
        pFontIcon9->SetWidth("20dp");
        pFontIcon9->SetAspectRatio(1.000000);
        pFontIcon9->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon9->SetCharcode(59655);
        pFontIcon9->SetColor(glm::vec4(129.000000, 245.000000, 210.000000, 255.000000));
        e3::Text* pText4 = e3::ViewFactory::CreateText();
        pElement12->AddElement(pText4);
        pText4->SetMarginLeft("5dp");
        pText4->SetText("10/10");
        pText4->SetFontStyle((e3::EFontStyle)2);
        pText4->SetFontSize("14dp");
        pText4->SetTextColor(glm::vec4(129.000000, 245.000000, 210.000000, 255.000000));
    mFuel = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement12->AddElement(mFuel);
        mFuel->SetMarginLeft("10dp");
        mFuel->SetWidth("18dp");
        mFuel->SetAspectRatio(1.000000);
        mFuel->SetShapeType((e3::EShapeType)1);
        mFuel->SetBackgroundColor(glm::vec4(93.000000, 215.000000, 128.000000, 255.000000));
        e3::FontIcon* pFontIcon10 = e3::ViewFactory::CreateFontIcon();
        mFuel->AddElement(pFontIcon10);
        pFontIcon10->SetWidth("14dp");
        pFontIcon10->SetAspectRatio(1.000000);
        pFontIcon10->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon10->SetCharcode(59653);
        pFontIcon10->SetColor(glm::vec4(0, 0, 0, 255));
        e3::FontIcon* pFontIcon11 = e3::ViewFactory::CreateFontIcon();
        pElement5->AddElement(pFontIcon11);
        pFontIcon11->SetMarginLeft("20dp");
        pFontIcon11->SetWidth("24dp");
        pFontIcon11->SetAspectRatio(1.000000);
        pFontIcon11->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon11->SetCharcode(59648);
        pFontIcon11->SetColor(glm::vec4(255));

}
