#include "MainMenuCampaignBase.h"

#include <e3/ViewFactory.h>
#include "NoLimitsValues.h"

MainMenuCampaignBase::MainMenuCampaignBase(e3::Element* pParent)
	: e3::Element(pParent)
{
        this->SetWidth("350dp");
        this->SetHeight("100%");
        this->SetMargin("10dp");
        this->SetOrientation((e3::EOrientation)1);
        this->SetOpacity(0.000000);
        mCampaign = new MenuItem();
        AddElement(mCampaign);
        mCampaign->SetWidth("100%");
        mCampaign->SetHeight("120dp");
        mCampaign->SetBackgroundColor(glm::vec4(99.000000, 77.000000, 185.000000, 255.000000));
        mCampaign->SetMarginBottom("10dp");
        mCampaign->SetBorderRadius(glm::vec4(10));
        mCampaign->SetOrientation((e3::EOrientation)1);
        mCampaign->SetAlignItemsVer((e3::EAlignment)3);
        mCampaign->SetPadding("5dp");
    e3::Element* pElement1 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mCampaign->AddElement(pElement1);
        pElement1->SetOrientation((e3::EOrientation)1);
        pElement1->SetWidth("100%");
        pElement1->SetAlignItemsHor((e3::EAlignment)0);
        e3::Text* pText1 = e3::ViewFactory::CreateText();
        pElement1->AddElement(pText1);
        pText1->SetText("CAMPAIGN");
        pText1->SetFontSize("16dp");
        pText1->SetTextColor(glm::vec4(255));
        pText1->SetFontStyle((e3::EFontStyle)2);
    e3::Element* pElement2 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mCampaign->AddElement(pElement2);
        pElement2->SetWidth("100%");
        pElement2->SetOrientation((e3::EOrientation)1);
        pElement2->SetAlignItemsHor((e3::EAlignment)0);
        e3::Text* pText2 = e3::ViewFactory::CreateText();
        pElement2->AddElement(pText2);
        pText2->SetText("53%");
        pText2->SetFontSize("12dp");
        pText2->SetTextColor(glm::vec4(255));
        pText2->SetFontStyle((e3::EFontStyle)2);
        e3::Text* pText3 = e3::ViewFactory::CreateText();
        pElement2->AddElement(pText3);
        pText3->SetText("COMPLETED");
        pText3->SetFontSize("12dp");
        pText3->SetTextColor(glm::vec4(255));
        pText3->SetFontStyle((e3::EFontStyle)2);
                NextIcon* pCustomView1 = new NextIcon();
        mCampaign->AddElement(pCustomView1);
                MenuItem* pCustomView2 = new MenuItem();
        AddElement(pCustomView2);
        pCustomView2->SetWidth("100%");
        pCustomView2->SetHeight("100%");
        pCustomView2->SetBorderRadius(glm::vec4(10));
        pCustomView2->SetScaling((e3::EScaling)1);
        pCustomView2->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
        pCustomView2->SetOrientation((e3::EOrientation)1);
        pCustomView2->SetPadding("10dp");
    e3::Element* pElement3 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pCustomView2->AddElement(pElement3);
        pElement3->SetWidth("100%");
        pElement3->SetHeight("75%");
        mFreeItem1 = new MenuItem();
        pElement3->AddElement(mFreeItem1);
        mFreeItem1->SetWidth("50%");
        mFreeItem1->SetHeight("100%");
        mFreeItem1->SetBorderRadius(glm::vec4(10));
        mFreeItem1->SetMarginRight("10dp");
        mFreeItem1->SetBackgroundColor(glm::vec4(255.000000, 149.000000, 47.000000, 255.000000));
    e3::Element* pElement4 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mFreeItem1->AddElement(pElement4);
        pElement4->SetWidth("70%");
        pElement4->SetAspectRatio(1.000000);
        pElement4->SetBackgroundImage("NoLimits/gold3.png");
        mFreeItem2 = new MenuItem();
        pElement3->AddElement(mFreeItem2);
        mFreeItem2->SetWidth("50%");
        mFreeItem2->SetHeight("100%");
        mFreeItem2->SetBorderRadius(glm::vec4(10));
        mFreeItem2->SetBackgroundColor(glm::vec4(255.000000, 255.000000, 123.000000, 255.000000));
    mShine = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mFreeItem2->AddElement(mShine);
        mShine->SetPositionType((e3::EPositionType)1);
        mShine->SetWidth("100%");
        mShine->SetAspectRatio(1.000000);
        mShine->SetBackgroundImage("NoLimits/shine.png");
    e3::Element* pElement5 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mFreeItem2->AddElement(pElement5);
        pElement5->SetWidth("70%");
        pElement5->SetAspectRatio(1.000000);
        pElement5->SetBackgroundImage("NoLimits/gold3.png");
    e3::Element* pElement6 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pCustomView2->AddElement(pElement6);
        pElement6->SetWidth("100%");
        pElement6->SetHeight("25%");
        pElement6->SetOrientation((e3::EOrientation)1);
    e3::Element* pElement7 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement6->AddElement(pElement7);
        pElement7->SetHeight("50%");
        pElement7->SetWidth("100%");
        pElement7->SetAlignItemsHor((e3::EAlignment)0);
        e3::Text* pText4 = e3::ViewFactory::CreateText();
        pElement7->AddElement(pText4);
        pText4->SetText("BLACK FRIDAY");
        pText4->SetTextColor(glm::vec4(255));
        pText4->SetFontSize("18dp");
        pText4->SetFontStyle((e3::EFontStyle)2);
                BadgeNew* pCustomView3 = new BadgeNew();
        pElement7->AddElement(pCustomView3);
        pCustomView3->SetTop(0);
        pCustomView3->SetRight(0);
        pCustomView3->SetMarginLeft("10dp");
        pCustomView3->SetPositionType((e3::EPositionType)0);
    e3::Element* pElement8 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement6->AddElement(pElement8);
        pElement8->SetWidth("100%");
        pElement8->SetAlignItemsHor((e3::EAlignment)0);
        e3::Text* pText5 = e3::ViewFactory::CreateText();
        pElement8->AddElement(pText5);
        pText5->SetText("NEXT UPDATE:");
        pText5->SetTextColor(glm::vec4(255));
        pText5->SetFontSize("14dp");
        pText5->SetFontStyle((e3::EFontStyle)2);
        e3::FontIcon* pFontIcon1 = e3::ViewFactory::CreateFontIcon();
        pElement8->AddElement(pFontIcon1);
        pFontIcon1->SetWidth("14dp");
        pFontIcon1->SetAspectRatio(1.000000);
        pFontIcon1->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon1->SetCharcode(59662);
        pFontIcon1->SetColor(glm::vec4(255));
        pFontIcon1->SetMarginLeft("10dp");
        e3::Text* pText6 = e3::ViewFactory::CreateText();
        pElement8->AddElement(pText6);
        pText6->SetText("05:43:09");
        pText6->SetTextColor(glm::vec4(134.000000, 185.000000, 206.000000, 255.000000));
        pText6->SetFontSize("14dp");
        pText6->SetFontStyle((e3::EFontStyle)2);
        pText6->SetMarginLeft("10dp");
                NextIcon* pCustomView4 = new NextIcon();
        pCustomView2->AddElement(pCustomView4);

}
