#include "MainMenuGarageBase.h"

#include <e3/ViewFactory.h>
#include "NoLimitsValues.h"

MainMenuGarageBase::MainMenuGarageBase(e3::Element* pParent)
	: e3::Element(pParent)
{
        this->SetWidth("120dp");
        this->SetHeight("100%");
        this->SetMarginRight("20dp");
        this->SetAlignItemsVer((e3::EAlignment)0);
        this->SetOrientation((e3::EOrientation)1);
    e3::Element* pElement1 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    AddElement(pElement1);
        pElement1->SetWidth("100%");
        pElement1->SetMarginBottom("10dp");
    e3::Element* pElement2 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement1->AddElement(pElement2);
        pElement2->SetWidth("100%");
        pElement2->SetHeight("50dp");
        pElement2->SetBorderRadius(glm::vec4(20));
        pElement2->SetOrientation((e3::EOrientation)1);
        pElement2->SetOverflow((e3::EOverflow)0);
        pElement2->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
    e3::Element* pElement3 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement3);
        pElement3->SetWidth("100%");
        pElement3->SetHeight("60%");
        pElement3->SetAlignItemsHor((e3::EAlignment)0);
        pElement3->SetBackgroundColor(glm::vec4(255, 255, 255, 10));
        e3::FontIcon* pFontIcon1 = e3::ViewFactory::CreateFontIcon();
        pElement3->AddElement(pFontIcon1);
        pFontIcon1->SetWidth("25dp");
        pFontIcon1->SetAspectRatio(1.000000);
        pFontIcon1->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon1->SetCharcode(59658);
        pFontIcon1->SetColor(glm::vec4(255));
        pFontIcon1->SetMarginRight("10dp");
        pFontIcon1->SetMarginLeft("10dp");
        e3::Text* pText1 = e3::ViewFactory::CreateText();
        pElement3->AddElement(pText1);
        pText1->SetText("GARAGE");
        pText1->SetTextColor(glm::vec4(255));
        pText1->SetFontSize("14dp");
        pText1->SetFontStyle((e3::EFontStyle)2);
    e3::Element* pElement4 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement4);
        pElement4->SetWidth("100%");
        pElement4->SetHeight("40%");
        e3::Text* pText2 = e3::ViewFactory::CreateText();
        pElement4->AddElement(pText2);
        pText2->SetText("EXISTS 10/250 CARS");
        pText2->SetTextColor(glm::vec4(255));
        pText2->SetFontSize("10dp");
        pText2->SetFontStyle((e3::EFontStyle)2);
    e3::Element* pElement5 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    AddElement(pElement5);
        pElement5->SetWidth("100%");
        pElement5->SetMarginBottom("10dp");
        pElement5->SetAlignItemsHor((e3::EAlignment)3);
    e3::Element* pElement6 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement5->AddElement(pElement6);
        pElement6->SetWidth("55dp");
        pElement6->SetHeight("50dp");
        pElement6->SetBorderRadius(glm::vec4(20));
        pElement6->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
        e3::FontIcon* pFontIcon2 = e3::ViewFactory::CreateFontIcon();
        pElement6->AddElement(pFontIcon2);
        pFontIcon2->SetWidth("35dp");
        pFontIcon2->SetAspectRatio(1.000000);
        pFontIcon2->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon2->SetCharcode(59664);
        pFontIcon2->SetColor(glm::vec4(255));
    e3::Element* pElement7 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement5->AddElement(pElement7);
        pElement7->SetWidth("55dp");
        pElement7->SetHeight("50dp");
        pElement7->SetBorderRadius(glm::vec4(20));
        pElement7->SetBackgroundColor(glm::vec4(255, 255, 255, 50));
        e3::FontIcon* pFontIcon3 = e3::ViewFactory::CreateFontIcon();
        pElement7->AddElement(pFontIcon3);
        pFontIcon3->SetWidth("35dp");
        pFontIcon3->SetAspectRatio(1.000000);
        pFontIcon3->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon3->SetCharcode(59651);
        pFontIcon3->SetColor(glm::vec4(255));
        mGolds = new MenuItem();
        AddElement(mGolds);
        mGolds->SetWidth("100%");
        mGolds->SetHeight("52dp");
        mGolds->SetOpacity(1.000000);
        mGolds->SetBackgroundColor(glm::vec4(254.000000, 192.000000, 29.000000, 255.000000));
    e3::Element* pElement8 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    mGolds->AddElement(pElement8);
        pElement8->SetOrientation((e3::EOrientation)1);
        pElement8->SetMarginRight("30dp");
        e3::Text* pText3 = e3::ViewFactory::CreateText();
        pElement8->AddElement(pText3);
        pText3->SetText("GOLD");
        pText3->SetTextColor(glm::vec4(0, 0, 0, 255));
        pText3->SetFontSize("16dp");
        pText3->SetFontStyle((e3::EFontStyle)2);
        e3::Text* pText4 = e3::ViewFactory::CreateText();
        pElement8->AddElement(pText4);
        pText4->SetText("FREE");
        pText4->SetTextColor(glm::vec4(0, 0, 0, 255));
        pText4->SetFontSize("16dp");
        pText4->SetFontStyle((e3::EFontStyle)2);
        e3::FontIcon* pFontIcon4 = e3::ViewFactory::CreateFontIcon();
        mGolds->AddElement(pFontIcon4);
        pFontIcon4->SetWidth("35dp");
        pFontIcon4->SetAspectRatio(1.000000);
        pFontIcon4->SetFont(_s(NoLimits/icomoon.ttf));
        pFontIcon4->SetCharcode(59663);
        pFontIcon4->SetColor(glm::vec4(40, 40, 40, 255));

}
